### ISSUE TITLE
Connection error with Tailscale

### ISSUE THREAD

**Issue by Weldawadyathink** [SoundLeaf/SoundLeafApp#14]
**Describe the bug**
Any server connection using Tailscale fails

**To Reproduce**
1. Set up an audiobookshelf instance accessible through Tailscale
2. Input Tailscale hostname into app
3. App says connection failed

Tested with an ip address (100.x.x.x) and hostname (device.networkname.ts.net

**Expected behavior**
Connection should work. The same hostname connection works for audiobookshelf iOS, plappa, and shelf player. 

**Smartphone (please complete the following information):**
 - Device: iPhone 14 Pro 
 - OS: iOS 18.4.1

**Comment by jnbht** [comment]
Same problem here!
Neither Magic DNS nor TS Ip is accepted.

**Comment by justin-pierce** [comment]
Try `http://DEVICE_NAME:PORT` ?

note http not https

**Comment by jnbht** [comment]
I tried http:// in every possible way.
What do you mean with „device_name“? 
The MagicDNS from Tailscale 
?

**Comment by justin-pierce** [comment]
> I tried http:// in every possible way.
> What do you mean with „device_name“? 
> The MagicDNS from Tailscale 
> ? 

Yeah the MagicDNS name. It's been working for me through tailscale without issue.

**Comment by jax-tr** [comment]
Yes exactly the same problem on my side

![Image](https://github.com/user-attachments/assets/7f7b4602-effc-407c-bd32-25d3561f474a)

That url works fine in safari, but not in Audiobookshelf. And I tried from local WiFi and 5G.
Although, it seems like even when turning off Tailscale, SoundLeaf can't connect to my audiobookshelf instance using the local ip on a local network.

So it could be a problem with my Audiobookshelf server, or a problem with HTTP instead of HTTPS, or just the app doing something weird. I'll try installing a certificate and see what comes up.

**Comment by shoesandsocks** [comment]
I thought I was affected by this, also. I'm running abs in a docker container with a tailscale "sidecar," so I don't need a port number. I tried all the various configurations of the URL (which all work in a browser), but it wasn't until I saw @justin-pierce 's suggestion that I got it to work... as simple as `http://audiobookshelf`, the magicDNS name by itself. Thanks for the assist.

**Comment by jnbht** [comment]
http:// is not the solution for those of us who don’t get a connection.

I do not think it’s a problem on our side to be honest. It works everywhere else for me
Audiobookshelf App
Shelfplayer 
Safari
No matter if local or on the go 😌

If we can help in finding the problem, let us know!

**Comment by jnbht** [comment]
One thing thou, if I use my local IP (not Tailscale ip) of the server, it connects without any problems. The Tailscale service seems to produce the hiccup

**Comment by meeDamian** [comment]
Also experiencing this ☹️. I'll buy premium the second this is fixed.

**Comment by sgtstadanko** [comment]
Having same issue with DNS:port and externl ip:port. external IP is NATted to internal ABS server. Works fine on ABS client from testflight, Plappa, ShelfPlayer.  I think this is just an issue with the checking code for the connection.  If you remove it or allow bypass so the login button will activate i imagine it will work. Most folks who are savvy enough to setup an ABS server probably dont need the connection check part in the first place. Just a thought.... I was able to login internally. Looks really good. Just useless if we can hit it from outside LAN. It also works fine connected externally with openVPN when just using the internal IP so its not a VPN/Tailscale issue

**Comment by hemant6488** [comment]
Added a new option to the app config, lets see if it solves majority of the connection errors (in upcoming v1.2):

```
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>
```

Verified with tailscale IP and hostname:


<img width="585" height="1266" alt="Image" src="https://github.com/user-attachments/assets/603e9586-98f6-4654-873d-bf7925e9c91b" />
<img width="585" height="1266" alt="Image" src="https://github.com/user-attachments/assets/6e468117-4b8f-40b1-97d1-fe6acea8d7df" />

**Comment by hemant6488** [comment]
Update, and @sgtstadanko had it right: it was the connection check.

The app probed https first and waited far too long before falling back to plain http. Tailscale hosts go quiet rather than refusing, so the fallback took long enough that it looked like a flat failure. That's also why the ATS change in 1.2 didn't fix it for everyone.

The probe gives up after 8 seconds now. I tested against my own tailnet with a bare 100.x address and it connects in seconds, but an IP is all I had to test with, so MagicDNS and ts.net names are still unverified. That's the part several of you actually reported.

v2.1, on TestFlight: https://testflight.apple.com/join/fwu2bdjX

@jnbht @jax-tr @meeDamian if you still have this set up, could you try both the IP and the MagicDNS name and tell me which works?
