### ISSUE TITLE
iOS: Invalid refresh token causes infinite retry loop and rate limiting

### ISSUE THREAD

**Issue by lukefind** [SoundLeaf/SoundLeafApp#56]
SoundLeaf on iOS stores an invalid/corrupted refresh token and continuously attempts to refresh it every 10 seconds, eventually triggering Audiobookshelf's rate limiter. This results in the app becoming unusable and requiring daily reinstalls.

## Environment

- **SoundLeaf Version**: 5 (from User-Agent)
- **iOS Version**: 18.5 (Darwin 24.5.0)
- **Device**: iPhone
- **Audiobookshelf Version**: v32.0.2.2
- **Network**: Home WiFi (also occurs over cellular)

## Expected Behavior

When a refresh token expires or becomes invalid, SoundLeaf should:

1. Detect the authentication failure
2. Prompt the user to log in again
3. Obtain a new valid token

## Actual Behavior

1. SoundLeaf stores an invalid refresh token with a future issued-at timestamp (`iat: 1764938881` = Jan 24, 2026)
2. App continuously attempts to refresh this token every ~10 seconds
3. Each attempt fails with "Session not found for refresh token"
4. After ~4 minutes of failed attempts, Audiobookshelf rate limiter blocks further requests (HTTP 429)
5. App becomes unusable and requires reinstallation
6. Issue recurs daily, requiring daily reinstalls

## Steps to Reproduce

1. Install and authenticate SoundLeaf with Audiobookshelf server
2. Use the app normally throughout the day
3. Wait 24 hours
4. App stops working, requires reinstall

## Server Logs

Audiobookshelf logs showing the issue:

```
[2025-12-05 14:05:31.288] ERROR: [TokenManager] Failed to refresh token. Session not found for refresh token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIzYjU5NWJlNi03ODc1LTQxNjItOWJhNS1iYzdjMmJjNTUwNDEiLCJ1c2VybmFtZSI6InBpcCIsInR5cGUiOiJyZWZyZXNoIiwiaWF0IjoxNzY0OTM4ODgxLCJleHAiOjE3Njc1MzA4ODF9.7xaL4FkFGFCP97Q0aQhVjUPnFU4d04Tm2NTYBe-s218
[2025-12-05 14:05:41.175] ERROR: [TokenManager] Failed to refresh token. Session not found for refresh token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
[2025-12-05 14:05:51.014] ERROR: [TokenManager] Failed to refresh token. Session not found for refresh token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
... (continues every 10 seconds)

[2025-12-05 14:09:11.106] WARN: [RateLimiter] Rate limit exceeded - IP: <removed>, Endpoint: POST /auth/refresh, User-Agent: SoundLeaf/5 CFNetwork/3826.500.131 Darwin/24.5.0
```

**User-Agent**: `SoundLeaf/5 CFNetwork/3826.500.131 Darwin/24.5.0`

**Decoded JWT payload** (from failed refresh token):

```json
{
  "userId": "<removed>",
  "username": "<removed>",
  "type": "refresh",
  "iat": 1764938881,  // Jan 24, 2026 - invalid future timestamp
  "exp": 1767530881
}
```

## Pattern Observed

- Failed refresh attempts occur every ~10 seconds starting from first failure
- After ~4 minutes of continuous failures, rate limit is triggered
- Same invalid token persists across app sessions (even after closing/reopening)
- Only full reinstall clears the bad token

## Additional Notes

- **Android version works fine** - no daily reinstalls required, suggesting iOS-specific token storage/handling issue
- Issue appears to be with token persistence layer on iOS
- The `iat` (issued-at) timestamp being in the future (Jan 2026 when actual date is Dec 2025) suggests token generation or storage corruption

## Suggested Fix

When receiving a 401/403 or "Session not found" error on token refresh:

1. Clear stored refresh token from keychain/storage
2. Force user to re-authenticate
3. Avoid infinite retry loops on authentication failures

**Comment by jcleaves** [comment]
Either you work in QA or you should. This is very nicely written. _Bravo_.

I did a little regression testing with ABS in case they pushed something funky. Tested each version from the apt repo from 2.31.0 back to 2.27.0 with the same results. I honestly don't think this was their fault.

Short list of results (tested both phones, apps, and web for each version of ABS):
- Error 4 on both iPhones (13 and 13PM)
- Works in another ABS app (tonspur)
- Works in WebUI

If there's anything else I can test, don't hesitate to reach out.

**Comment by hemant6488** [comment]
Thanks for the incredibly detailed report - this helped a lot! You nailed it - the app was stuck in a retry loop when the refresh token became invalid. 

Fixed by:
- Adding a mutex to prevent concurrent refresh attempts
- Detecting invalid tokens and prompting re-login instead of retrying forever
- Storing credentials securely so the app can re-authenticate silently when possible

Should be available in TestFlight v1.5.1 (1) (pending approval from Apple): https://testflight.apple.com/join/fwu2bdjX


PS (Genuinely thankful for both of your reports @lukefind , @jcleaves )

**Comment by lukefind** [comment]
Ah thank you @jcleaves @hemant6488 , so glad this was helpful and super impressed by the quick tested and fix pushed out 🔥

**Update: Partial fix confirmed, but new issue found**

The future timestamp bug is fixed - tokens now have correct `iat` values. However, there's a new issue:

**Server logs:**

```
[2025-12-07 20:42:07] INFO: User "<removed>" logged in (new valid token issued)
[2025-12-08 00:30:00] INFO: Database cleaned up 2 expired sessions
[2025-12-08 08:50:50] ERROR: Failed to refresh token. Session not found
```

**New decoded JWT** (valid timestamp):

```json
{
  "iat": 1765140127,  // Dec 7, 2025 20:42:07 UTC ✓ CORRECT
  "exp": 1767732127   // ~30 days later
}
```

**Issue**: When Audiobookshelf expires the session server-side (appears to happen after ~12 hours), SoundLeaf doesn't detect this and force re-login. Instead, it keeps trying to refresh with the dead token.

**Expected**: When receiving "Session not found" error, SoundLeaf should clear the stored token and prompt for re-login instead of silently failing.

**Comment by hemant6488** [comment]
What did I do to deserve you? Thank you again for the detailed steps, helped track it down quickly.

**What went wrong:** When Audiobookshelf expires a session server-side (after ~12 hours), the app detects the 401 and attempts to silently re-authenticate using your stored credentials (password is securely saved in iOS Keychain). The re-login was actually succeeding, but the app was still throwing an error afterward - so it would log you back in and then immediately fail the request anyway, causing the loop.

**Expected behavior:** When the session expires and silent re-auth succeeds, the app should continue working seamlessly without any user intervention. If the stored password no longer works (e.g., you changed it), the app should show the login screen instead of looping.

**After the fix:**

Session expired, silent re-auth succeeds → app continues normally:
```
Token refresh failed - Session not found
Silent re-authentication SUCCEEDED
→ App continues with fresh tokens, no interruption
```

Session expired, password changed → login screen shown:
```
Token refresh failed - Session not found
Silent re-authentication FAILED: Authentication failed
→ Login screen displayed
```

Fix will be available in 1.5.1 (2). Let me know if you run into any other issues!

**Comment by lukefind** [comment]
just checked the app and it seems to have updated and all be working 🙌 great work!
